### ISSUE TITLE
Use factory functions for middleware

### ISSUE THREAD

**Issue by naptowncode** [fusionalliance/node-express-api-skeleton#11]
Currently middleware is added using functions that take an app argument and mutate it, like so:

```javascript
function configure(app) {
  app.use(compression());
}
```

Refactor this into a factory function that returns a middleware function:

```javascript
module.exports = function configureFactory() {
  return compression();
};
```

This reduces side effects and makes it easier to inject configuration:

```javascript
module.exports = function corsFactory(config) {
  // ...
  return cors({
    origin: config.allowedOrigins,
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowedHeaders: config.allowedHeaders,
    preflightContinue: true,
  });
};
```

Remember, any function with `([err,] req, res, next)` parameters is middleware and can be passed to `app.use()` or `app[METHOD]()`.

**Comment by JeremiahDotNet** [comment]
@naptowncode  It looks like the factory is going to return "something" that can be consumed with app.use(). Some of the middleware has multiple instances of app.use(). 

For example: configRouteHandler consumes two routes using app.use
`function configure(app) {
  app.use('/api/', routes);
  app.use(unmatchedRouteHandler);
}`

Do I break this file into two different factories?

**Comment by naptowncode** [comment]
For those two I would break them up. If two middlewares really don't make sense split apart you can always just stick them together with a Router and return that.

**Comment by JeremiahDotNet** [comment]
One more question. app.js has a single line that calls all the middleware.config functions.
`middleware.configure(app);`

Is the intention to replace it with something like this:
`app.use(middleware(config));`

**Comment by JeremiahDotNet** [comment]
Okay so that wasn't my last question :)
@naptowncode app-middleware/configureSwagger uses the app.get for swaggerJSDoc. And then it has it's own pattern to pass to app.use `app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(swaggerSpec));`

How would I go about refactoring that to match your pattern?
