### ISSUE TITLE
Verify the eslintrc "sourceType" parserOption

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/node-express-api-skeleton#4]
Please verify...

![image](https://user-images.githubusercontent.com/6438381/38503349-d2e9569c-3bdf-11e8-90c6-643bcf4a6221.png)

**Comment by JeremiahDotNet** [comment]
From what I can tell we are not using ECMAScript Modules so it should probably remain as "scripts". @naptowncode Can you provide some insight?

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md
https://nodejs.org/api/esm.html

**Comment by naptowncode** [comment]
Confirmed what @JeremiahDotNet said. Node.js doesn't truly support ES modules yet and won't for the foreseeable future.

**Comment by BWortman** [comment]
Cool. Thanks, @JeremiahDotNet and @naptowncode. Closing this.
