### ISSUE TITLE
Move bin/www to bin/www.js

### ISSUE THREAD

**Issue by naptowncode** [fusionalliance/node-express-api-skeleton#6]
Some tools are easily confused by JS files with no extension. ESLint in particular isn't currently linting the bin/www script. The way around this is to move bin/www to bin/www.js and add `"bin": { "www": "./bin/www.js" }` to the package.json.

**Comment by JeremiahDotNet** [comment]
@naptowncode I'm having trouble understanding what needs to be added to the package.json. When I renamed the bin/www to bin/www.js eslint started picking up the file.

**Comment by naptowncode** [comment]
Yeah, forget I said that part. Doesn't apply here after all. Carry on.
