### ISSUE TITLE
Remove [some/all] default values from src/config.js

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/node-express-api-skeleton#7]
![image](https://user-images.githubusercontent.com/6438381/38503604-888274d4-3be0-11e8-9d97-8fc26c5735a1.png)

**None of the current default values are sensitive at this point, but at some point we will need to support default values that can't be stored in source control (e.g. API keys). Let's get this working now, while it's simple, before we run into trouble down the road.**

**To resolve this Issue, make sure that this works, and then remove the dummy values from config.js:**

![image](https://user-images.githubusercontent.com/6438381/38504477-cda64106-3be2-11e8-94fc-659b06bce7de.png)

**Comment by naptowncode** [comment]
API keys, session secret, database creds, all those things should be `required: true` with no default. That way forgetting to specify them in production will fail loudly with an error.

Everything else should have a sensible default value that you wouldn't mind putting into production. Current defaults are geared toward development, that's probably not ideal.
